services:
  conda:
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    image: cs537-v1
    command: /bin/bash
    container_name: cs537
    platform: linux/amd64 # this just disables the warning, the image we use is only for amd64 anyway.
    volumes:
      - ./cs537:/cs537
